# Generated by Django 5.0.6 on 2024-06-04 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='uav',
            name='description',
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uav',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uav',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uav',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
