# Generated by Django 5.0.6 on 2024-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_rental_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('rented_to', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='uav',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
